[[yaml_cpp]]
arch = "aarch64"
git-tree-sha1 = "21ab938feaade415edaeed0115fc6ee019636589"
os = "macos"

    [[yaml_cpp.download]]
    sha256 = "3878cb0687087f01de6122b548e9a4447a3a73af12e0694baaa31fb330a66f33"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.aarch64-apple-darwin.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "544f5b52f06bce91061a173631fdcb1d1272e1ab"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "cdf113f4fbf5d39ed5677ddb2b93c85e361227e3023987cd414234671a89ba60"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.aarch64-linux-gnu-cxx03.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab0afd39fd473c4566da4393f2c39a71aee7aa45"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "f7c81eeaf57d94626f9ea7c09fb25296644e38628a628db5cc247c9466973ff4"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.aarch64-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb1dc8eae14e6de36f074dfe94eb51ecb8227f3f"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "0a312da07f921ad1cf852592cd0a74c2557e72e6be82b6f94d23fc110bdc5445"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.aarch64-linux-musl-cxx03.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4782de81fb8959498d96e5811419728825f2f3f"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "89f7a479c1a3ef2bb645125a06c3d26f8efd3bb1512f962d6f572bc43e7b083a"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.aarch64-linux-musl-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce52bcade485e8378b64cf40eb919ab665a47a39"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "ced212280d9c9d5775e19d88579a25e814760a07e848fa63e63807680b781435"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[yaml_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e94c10a430b5444f1771a973edc21b25454c3b01"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "754098f9a230d6ec013167e9ff5c7323f81b34f791dc4100b2d048081bf85ee4"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55c288371a2ffb41987a9b07a0e857af449cabdd"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "80cc83c1b937394a3f396f1ac70562f6a05d2d7b4a67143b19b0a996e3002a45"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[yaml_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0eab9f8cd1de9622e9cad125629d81634599125c"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "bb029e6de9012225b5f1c03c94cc4fa5673c6921253b5d0854aae202c9992c93"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a4cdc1086d834be865ca76261416418893808cd"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "5ce44b362a3161bcb14e8803aecb40a90c034e69e6f736245343bd18e426875f"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[yaml_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66850a5ba9e20e3485950bd643602896356aad0c"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "4eb7e28b374a0f0531a975730ce274db4de9a36fd762ebdbc55e06861a7dc802"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "327ef8feea19dcf15ceacc21c5771521c07d52fc"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "a200119951398756e20e951b1fa75d58f275fb356c5f629976803ef3dad992f1"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[yaml_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fd2bb78e185ec3658b8b6f5b91d0a0c312547cc"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "07c580fdd69ce90d34b43542c6aebf3a662621a5dc371284c4d22a25f877af8a"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "573c3c35a4ca7e336dd62c9fe9d587b3eabc5a5e"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "844afb8f6bde5422febe105bac9649c54b39b6a9393244449bd588048dd9d73b"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.i686-linux-gnu-cxx03.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9e777d1d44c0154177310718bf62f2345175b7e"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "e0f64a5e566424d5343916fb326b0a17f896664d0a35d62771c887899990493c"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.i686-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03779314f9948765f9724a078ade6c224fdfd003"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "9e58acdf859bac8b155f1e365cec805a4ec6d4a8461fbc2b8e08fccebf808a7c"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.i686-linux-musl-cxx03.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e68c20e490358fce7a12c8f221ba15ffafdca3c"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "986768c4c2bc4588182e49a3b569fad680bcd29d0acfd8f2bb06d5fe9bb68f2a"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.i686-linux-musl-cxx11.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8165f62a5b33de99ed76263ce4e688b44a10b800"
os = "windows"

    [[yaml_cpp.download]]
    sha256 = "89db3536894084addadabd9775987c9891121863ae60eb20e562bb57c2b34e04"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.i686-w64-mingw32-cxx03.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b258093016eba66ef4d4dafe30a2e567844f37a3"
os = "windows"

    [[yaml_cpp.download]]
    sha256 = "3583dd5634e2386df6a1668cf312777c5e8f6f588034479848c199bb11b73f87"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.i686-w64-mingw32-cxx11.tar.gz"
[[yaml_cpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d51d0109199a9571f037dbfc8656ca586f9ae3c"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "c25db2fffb2d68dbf5bddfc5812f4715dd9b0af0af87687b37fb1edaff265b18"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[yaml_cpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd41bb9403a4f3044989b063dc4f163cb5612bd8"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "05e15df364dc780b756018d1c441c38c2baaedcab688e274e2d0214ed96814f1"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
git-tree-sha1 = "4213deb360c09561971d88ce484c8c1d0b3613a9"
os = "macos"

    [[yaml_cpp.download]]
    sha256 = "89c3a08c7f82f8ba63cf745f008bb8024f752e910c62d60713578a8dbd5404b9"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.x86_64-apple-darwin.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d80353e807df2be4a5083e277de894f5e980eff4"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "d524e88027cf9688961940cf72aee497474e4e3e0f405ac529b64a69c46d4829"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.x86_64-linux-gnu-cxx03.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "944cecc33ed34ede72470986e5a1b03b39e2c15b"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "fe62eb2c81b6fea3f10008e01c64e0b5b6c48630e8211e65fd7ca4db4c0fea7b"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.x86_64-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72c6d939ef8748e8df26b063518371b336ca04e7"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "0c06181db7e97f20d36f0f16e6467ebb4c9f136df2c3590b3ba9a3ebc17f9cad"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.x86_64-linux-musl-cxx03.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "822d228b2c21d52f70b578302bff3065e17aae3f"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "1b4724f1173b93195c325f1b91ec2bcc4b9f97e7e46acf30ffe87f61c3f8754b"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.x86_64-linux-musl-cxx11.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
git-tree-sha1 = "c87f780888bd904b7bba35a1464d1ee8d4a9672a"
os = "freebsd"

    [[yaml_cpp.download]]
    sha256 = "5f9896f90f73ca654322707f88ba479773a6f05ff69478fa3983eea8200521f8"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.x86_64-unknown-freebsd.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7720daed8e3e008e2581abf1caaa7de805d57f9f"
os = "windows"

    [[yaml_cpp.download]]
    sha256 = "bf7a735ea1997d2bbd9220fac50dcfd99edef1f173fa7f4aa8430563ffcfb98d"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fca6def62ac5b63aff594344f74866131afc4059"
os = "windows"

    [[yaml_cpp.download]]
    sha256 = "aff18c19ee90d5e14f88fa6e470b147cdd34f43096152d1153c3af70798491e4"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.6.3+0/yaml_cpp.v0.6.3.x86_64-w64-mingw32-cxx11.tar.gz"
