[[yaml_cpp]]
arch = "aarch64"
git-tree-sha1 = "5afbd4bced220822dd8fa15859dda0f4efbc485f"
os = "macos"

    [[yaml_cpp.download]]
    sha256 = "9cb61c7d782801966889468de54c495f768aafb34f1b3093cfce92c8d5204c80"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.aarch64-apple-darwin.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d283bbf89188eb4b1ab5f90258397e9e6022036b"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "afa81a12326b0b9879f8e7d338f9639326bc9649ec0b40b60e5ec7e03c62ae4b"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.aarch64-linux-gnu-cxx03.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd2908ea83e41b9c356a6ee02b0a333cfc9f9d2b"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "1324047391b480ec2b0f75fdf8b41722efae4131f4af3c090a965b3d8526c92b"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.aarch64-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f45fe5cb94db7ff0cd09a5fd96e9a281deae1799"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "fdcd6d42c768248cffacb3c168759bf8140a69de34da94fb1435b9f347cff3e7"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.aarch64-linux-musl-cxx03.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2273de2b6c3df4230c9ae34d6a7a7ac54851d018"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "c1c02fcba370c96b0870bcbd1299bbd9245b7db40fb2e25c7107f39b8df16231"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.aarch64-linux-musl-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c907339ba056a9e08319170ef259bc743b9df635"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "51f39b0372375f8eff12b2a99121f72bc91f576a69908876abb2d70f2cb56110"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[yaml_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7d258450639ea1bfc19634f3289886623c26071"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "8852712d797d327b0f60192a2815b8c83b1e373ba6f3f261ef7448022b938b13"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80081ba412c864ef875e79aebdb3cec3436a7ada"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "9ed56ea226eb4939a18f799fd5b03843ca37d430a6cbf4f23dd9f5b8c9fba89b"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[yaml_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb3c3e60190fba5396fc53cdb11dad3e6c1cf3d2"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "dae1458715d2ba22f6625c44aa187a5f47ae0a3d4fdddc64b27e2ef4b9a5ab49"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf26d8a247da0cc52a3f78f2c4ee7f6794ccc97c"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "11a992277c750b154c8dda83d3dc4ed09e04e17a4a191ef3a2aad7a7a9b36c76"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[yaml_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b94c28617212c233cd7017f77ed96c6a92ad8a2"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "6a2ab0c4c509b3f03337fc9604cf390374b63eea2bc0c2b2bd935ec7d5893d9e"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22ad48b081acd8932f57ba75f9b73fc831fbedcf"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "f25b317400e3472006cd322644d07ab127a9d3c05d79da924985a4635925e57e"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[yaml_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61a43fd830b81aa3a134b8efac69ff97b76d54db"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "a67048d05b83e9cd8e3269dd77bd3d6ffec0e4606ac82a11e2e071c87af9da36"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1dfd539105f72ae737ba244508d344ae7ecee0c"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "9c09c24850070bb051262a6c1e287c608b48c46d0805e899c85c5e3c0d34370c"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.i686-linux-gnu-cxx03.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "946f65ddf573125ae7eefc0377165b0a62190487"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "9d4ec523c4c1a33741769210ae36ac2f46708699daa250cf2032cfc172749312"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.i686-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aff39985426370b9c6273bfc65cd9f9105b93873"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "6db571821fab963e849f55c30fec29bfdc13700fd42a2fec2549b66afcbbfdcd"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.i686-linux-musl-cxx03.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c64fe32821d59f263fb05e4ac47bdb944d32694"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "95ab91322aa5e675c5e0b0f1e35917664a376d40bd0f321ec75ce8faa1beed59"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.i686-linux-musl-cxx11.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f4971a88647d418c284087581a1e398929fc71e"
os = "windows"

    [[yaml_cpp.download]]
    sha256 = "2b56547790ff7c1abef213b8ab4abe13db03db8c54a14bce1611f00b97092298"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.i686-w64-mingw32-cxx03.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c04e7085a6293fc8ed28a933e7a64cf52246d9d"
os = "windows"

    [[yaml_cpp.download]]
    sha256 = "3a494764c74e9c2c9a22b68e5b34f97836f0b5b6b2f5e142fa84801e4dc8b431"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.i686-w64-mingw32-cxx11.tar.gz"
[[yaml_cpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95ce4b8c73a39bee42d0357f520ce497eb9c11f0"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "533a17dee8427db9038d1d3e56dae461cc69a822ddeef1a01c720b775b2c4a67"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[yaml_cpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dffb3d1a8911c17d8deae2e4dfa048e91e1c6c3f"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "9c83c9b60ce5c95bdcc4e99cb55659a8c546be28be3475c47c900f2dd10409a9"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
git-tree-sha1 = "0e4e40e80cae955899e71d46b8160baea14edda0"
os = "macos"

    [[yaml_cpp.download]]
    sha256 = "e67bdd73078191ec610b9543a4691aba16eb8c42ad6039f60f714d6b457c81b8"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.x86_64-apple-darwin.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd5acb1ac913e4db90cb1e4c4ebbde0af819af33"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "f3747cf93bc951afce2399cf0add23db842c3aef4a798c66563fb489cd041bae"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.x86_64-linux-gnu-cxx03.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5e47a9fc2ba0120a303b737baef7aa6ea30c8d5"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "3ed5ffa5b46a0da317c0dac87165246a92e1a983b82064833444b519cbc91b49"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.x86_64-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c413e16fd880d6a14308913d640973db17f9b2d2"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "01edd06fef6fd59ed179b92444664e6ff6ef9ae29357ce6ef525fcc71cec4f14"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.x86_64-linux-musl-cxx03.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a65d66623740dab21acda3b3fd4af7397d72318"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "963d01c620eff635184bf6a51fe7aff383fc9dff408b3160b3f401b664dc8fc5"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.x86_64-linux-musl-cxx11.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
git-tree-sha1 = "8ab884b0391c4fc90d1244eb4141fd434e697a9a"
os = "freebsd"

    [[yaml_cpp.download]]
    sha256 = "ffc8724b7a26c6db154505e067905d859855817a96b899f67bd35614894c4d30"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.x86_64-unknown-freebsd.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0660dcaca95b7106967a54595381192d67cfd937"
os = "windows"

    [[yaml_cpp.download]]
    sha256 = "0e93f90c426e24602494e4173363c25f4b85dca23cce9d8226220995ac880dbf"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe10ae569840bd6976bbbd0ae55400b21dc7db6a"
os = "windows"

    [[yaml_cpp.download]]
    sha256 = "0eb1bd7f0b45a15b24bcfe8e944952b836bdc3201ffb5d9c893bf57685d119c1"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.7.0+2/yaml_cpp.v0.7.0.x86_64-w64-mingw32-cxx11.tar.gz"
