[[yaml_cpp]]
arch = "aarch64"
git-tree-sha1 = "6f53ff2d75f2783e3da06c8122469650e6b1618a"
os = "macos"

    [[yaml_cpp.download]]
    sha256 = "9d5ff897c3a08698fc1f62bf735ca8df18b7806cb63af0312dc882f95391d886"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.aarch64-apple-darwin.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "472909216485944b4e52cccfb298afd460d6c1fa"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "e0358f0074ab71b517b16235f851708e51acc59b8eb493b98be02c2c9d3d6d90"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.aarch64-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09f208e324f88a6e8da60c9f90688b492f43029f"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "ee2b125f449b4cea127789cc30f934af420b49aeffcd0daf73dd2ae693968b46"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.aarch64-linux-musl-cxx11.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
git-tree-sha1 = "2f295f1248596117943c67a9e7bffc5cbeed1c71"
os = "freebsd"

    [[yaml_cpp.download]]
    sha256 = "26af4f2bd194eff8645d3b4138ee79f702141435dc9b0ca80e732c052e3515be"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.aarch64-unknown-freebsd.tar.gz"
[[yaml_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09ee580aa972be4d1ceacb0a84b7be7bb30e4e18"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "6c54addfa1b496cebc69dff42c06151551d9357ff87ae34c5195130db5dd1f3a"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1eb88d4a66535b5e5abaf53c998200074827cd83"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "cd001f282c9cb11abcb2cc92cd60876de896e501d6115df5bc03bfb2fa793fce"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e57bc16f71a9d2cd35db933358b8eea0ce60123"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "e6ae104458fce3b3c7476e250a23eb9a7c176d12bdba2b84516f3632d45b1fb3"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5476af1a0e33c5545d0c1c16b10938047056f78b"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "58a4fe46abbe83408992799c2beed9d85275fdc30826943959525af1587aec98"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "158a893c23880b85ad8afef850ac928038935a2c"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "62ba308f095fd5efa0ad1e7c81a919c1500055adc274dd4c9e4670bbcf1e2200"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.i686-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb538cdf5143a41fb38b8617d5b745e777d71256"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "e062b10eb36df62f9d60ab372157b9b8aaec846aa08460fef63395d8f9d4085f"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.i686-linux-musl-cxx11.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9a6d1889e99ae4b75fcf2589d2516395a40b773"
os = "windows"

    [[yaml_cpp.download]]
    sha256 = "5f968db5670ad80156042089b468c06ddd3f50638551bcdb9ee11e9340fe2352"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.i686-w64-mingw32-cxx11.tar.gz"
[[yaml_cpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83f79c94828b815bf312a0141477be35e5fe869f"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "ad6e1152e581f57580a1110f1186d4184c4c8017142a9515c33aa9d92c4e7a79"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da6ef68becc9a7cb974cccfb075c0bda6dcf29ff"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "d98fc3f5e2fb05e5d18539ec5d1c2af772197031bfb48257e91c2a44bc238330"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.riscv64-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
git-tree-sha1 = "522081b8a0a6488f69e1ee32f5c7da29d67dda75"
os = "macos"

    [[yaml_cpp.download]]
    sha256 = "e7dc37b6825dd1e271c71d918400906cbaaeacc7307b0e9c3b33f1be0f18b50d"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.x86_64-apple-darwin.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06b6dad132d4f8e5077726015bd00813c607a21d"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "011d4746eb9b64fa8fe4f7fb91973f9153352e67388309d9c47344f20a766df5"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.x86_64-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c9bc82dbaeb6585b82715fcea5eaab4aa296d5f"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "340e5a08b5af056c9ca7d3fad67a5d6837f632f30062da6f30dbbe3ddc4f4e52"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.x86_64-linux-musl-cxx11.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
git-tree-sha1 = "841ca900c243fc0938893e968f4a430c91480462"
os = "freebsd"

    [[yaml_cpp.download]]
    sha256 = "dbc934e048359150ed65b175e36ee7cddc6f831909bef6b15f191cb5d0356713"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.x86_64-unknown-freebsd.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acb65a9de4aa4037e6c09ddc7df7d1def9b54cac"
os = "windows"

    [[yaml_cpp.download]]
    sha256 = "b194cb51791ebf51f33a270530cbb1431138970214c0e4c285e42359287e5769"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.9.0+0/yaml_cpp.v0.9.0.x86_64-w64-mingw32-cxx11.tar.gz"
