[[yaml_cpp]]
arch = "aarch64"
git-tree-sha1 = "1b9dbfa9aeca31b6970cc4e1f4bf95233a54865d"
os = "macos"

    [[yaml_cpp.download]]
    sha256 = "9a155ef9f1788adf99e83ebe4394ce44042796beb57a9ef5a9937f8a788f1576"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.aarch64-apple-darwin.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6bc5804d7bbf5a0030f47a6a40a0f37f5a63377a"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "2f5e1b92856aef12a9dba6d50a0b929e76b22b3be9da0e6cf1f8a21f91333c12"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.aarch64-linux-gnu-cxx03.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c82b36b7b4a55426eda851a963db89fd9d8b6c76"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "1d484b5c9c28dd7a53e675764d25ffacca759fe04430157378ad003ddb00e0cf"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.aarch64-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "794709a76d690c278aec4514094cb70d08e8f59d"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "ec78d0f05d1d5b903ff6382a90c3aa23ed8103ca5f3349e0acfc44214e3d1167"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.aarch64-linux-musl-cxx03.tar.gz"
[[yaml_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8393cd0dfdabbf101ca2c0dc34b381c666078266"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "bc9d25b95645470373b4d7de06b0ca3053d53ace4d6ef4ea7229d38654022319"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.aarch64-linux-musl-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82e74b5ffd3cf2346dadcc26abb9f9f871d020d0"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "129526826da2ccea93af46ffc31e2d46a8c04d4a0b5a65e6bf77629fbc9437e8"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[yaml_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "668e3d88b4dd1197976e3805c225ddf18d89322f"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "8120c18f9ddf0f003cce3fc47fb52ec98020fa126a24fe37cd4f3ff844f7bdc5"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9ca48b87225e096d46734c3679cd604a9df691a"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "9063a8d826e6096beeba25d37b94e4217b0049a0202df535206563da8670e434"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[yaml_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7006bb9319f642b4839200f02d2f6b1db438802f"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "e809562825404b1d30b47bf703e1247092ae00992263ae907aa25a4ffbf42324"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35548ac9a70c51e562ac3b91be778fe9844f101e"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "81bde8263a2950f05503adc6f26e09f9054d98290530f1ee05b0acbd35b08816"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[yaml_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "053beac079653bd8896fd7b66f7f6272a8515af9"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "17acd4d12186edd5e88580efcd380e1767059c0e6ee29cb8c4e433f581ccb3bc"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84386b6a7cc965b05fa9f183aa6e88b5e8238244"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "440681f9ab85218b812bfc8385598cabc64e50a66a683da6c651efa22f6069a1"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[yaml_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75bb25782e0f3d714ed56d9a9a8b81817bf1b79c"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "07d230e64a571c5998e86fde3aa89f3544a61cda339bcc59072302f8187a5df5"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f78a921685e369e86aa30df313eee2f215f991f"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "b2ba8f09c64e60a4671d5215b7ff8abc23e90ba5a3862876c34a11bf455ba1b3"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.i686-linux-gnu-cxx03.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03371612d86964871e59e149d19106e8290d080c"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "1eec59a4782bdc7436953f3e40a5d074828b5b93fbcb8d9b4948fefde1abd108"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.i686-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c518d6ba5b7548e0ab43e70ef8c4c14bac45062"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "4268661c826b88454a47171efbf1c9a782df6dc046b34f72f80d7482b84ae953"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.i686-linux-musl-cxx03.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3499eab172e999bcdc4535462b4c484ee25f1f92"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "b7de8df5091c24998d0338f0739d34cd5981529612d53dddb45905841a3f6e0f"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.i686-linux-musl-cxx11.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70ddf21f697fec35c71d50da3c240690644c66c2"
os = "windows"

    [[yaml_cpp.download]]
    sha256 = "ae3af0984778d3f4966b8c5a7e5c609e8bd80eb50a1902de8877975f2e25198e"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.i686-w64-mingw32-cxx03.tar.gz"
[[yaml_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b40194b6cd56569650c70be45bb0aee853f50f94"
os = "windows"

    [[yaml_cpp.download]]
    sha256 = "ffc446d92f9b81f4a6aa981506ae0516156d9572e4945abcf5e7c29bc28adf47"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.i686-w64-mingw32-cxx11.tar.gz"
[[yaml_cpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be9ac2efcc3b8261016e360f204d45817ebd9906"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "57666af30606ce4f49d0ef9e4c5e26af9e282fad0d311de458b8eb78e05380e7"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[yaml_cpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5103cb92aef66df2e69aab3983ce234cfccf6d08"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "dbcea8995bf6082c1d563c80d6ec476b86fb4a22d2fa84cdf99628b243032a30"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
git-tree-sha1 = "87c30c2fce3019bfd0ad9ef774336c1801df8ce0"
os = "macos"

    [[yaml_cpp.download]]
    sha256 = "d34c35956dd339fd9df2d3561c966a83dd70086c3ed57bf579f4ea2c68f5a27b"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.x86_64-apple-darwin.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b9a7747b77e95d8f46512bfd6f6fdc06ae46c060"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "d874066b98bc7308d9e91f68cf2c8b0af4d0b3f56b80be3b0f840e0774373173"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.x86_64-linux-gnu-cxx03.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc2ca85d7f22518b6a1f908facd33822c8c017ed"
libc = "glibc"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "c58dfb253575e8165f3edcff62f24bdf650e3f605c5758cb55fc86f619d071f8"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.x86_64-linux-gnu-cxx11.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a12e48a88b9e42eed7b117772e80854468175e0"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "866aa7a23ca48922952a27536f9ad79526a71a1b79e5d31935cde5e7ca7d5e36"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.x86_64-linux-musl-cxx03.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fa9ed8cf9c53cc472f38ac145e3621b60d4e5e1"
libc = "musl"
os = "linux"

    [[yaml_cpp.download]]
    sha256 = "80e8565ebc58c2a1644c2c9b5ca2ef61cd33b6f739e79c7d874313cf850e0d20"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.x86_64-linux-musl-cxx11.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
git-tree-sha1 = "84732af8dc0f1c5022053c351bf614ce542e3327"
os = "freebsd"

    [[yaml_cpp.download]]
    sha256 = "a5f97144ef024d86c8b6eca8bb9b21801fb8fda0b93bc506c6b143471538dfe1"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.x86_64-unknown-freebsd.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6a7ac09cc085328c57ec0dc0eaa6211b6543a51"
os = "windows"

    [[yaml_cpp.download]]
    sha256 = "260a54cce6299d2f873e6a68fa5c1835c95a996162800edffd6235d3e4e17b18"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[yaml_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64849e3bbe6703130966bdd05f2bd1ba23285bb8"
os = "windows"

    [[yaml_cpp.download]]
    sha256 = "7cf2a162c51fd0e0b55ead7c4fadc03c46377ef952343ec188e3dea6c8d6e6fe"
    url = "https://github.com/JuliaBinaryWrappers/yaml_cpp_jll.jl/releases/download/yaml_cpp-v0.5.3+0/yaml_cpp.v0.5.3.x86_64-w64-mingw32-cxx11.tar.gz"
